# Generated by Django 4.0.1 on 2022-01-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=45)),
                ('firstname', models.CharField(max_length=45)),
                ('email_address', models.CharField(blank=True, max_length=45, null=True)),
                ('phone_number', models.IntegerField()),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=45, null=True)),
                ('prefered_role', models.CharField(blank=True, max_length=45, null=True)),
                ('occupied', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actori',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('paycheck', models.IntegerField(blank=True, null=True)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'contract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=45)),
                ('movie_type', models.CharField(max_length=45)),
                ('production_company', models.CharField(max_length=45)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=45, null=True)),
                ('country_origin', models.CharField(blank=True, max_length=45, null=True)),
                ('raiting', models.FloatField(blank=True, null=True)),
                ('movie_director', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'filme',
                'managed': False,
            },
        ),
    ]
